// Renders the native icon and splash sources in apps/mobile/resources/ from the HoopTicker mark
// (same drawing as apps/web/src/app/icon.svg), then `pnpm --filter @courtvault/mobile assets`
// turns them into the Android and iOS resources with @capacitor/assets.
// Run after changing the mark: node tools/make-assets.mjs
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createRequire } from 'node:module';
const sharp = createRequire(import.meta.url)(
  resolve(
    import.meta.dirname,
    '../../../node_modules/.pnpm/sharp@0.35.5_@types+node@22.20.5/node_modules/sharp',
  ),
);

const INK = '#121417';
const LIME = '#e9ff5f';
// The ball on a 64-unit grid, centered on (32, 32), radius 26.
const ball = `<circle cx="32" cy="32" r="26" fill="${LIME}"/><g fill="none" stroke="${INK}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"><path d="M32 6v52"/><path d="M14.5 13.5C25.5 21.5 25.5 42.5 14.5 50.5"/><path d="M49.5 13.5C38.5 21.5 38.5 42.5 49.5 50.5"/><path d="M6 32h17l5.5-7.5 4.5 4.5 12.5-11.5"/></g>`;
/** A square canvas with the ball scaled to `ratio` of the side (ball diameter / side). */
const svg = (side, ratio, background) => {
  const scale = (side * ratio) / 52;
  const offset = side / 2 - 32 * scale;
  const bg = background ? `<rect width="${side}" height="${side}" fill="${background}"/>` : '';
  return Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${side}" height="${side}" viewBox="0 0 ${side} ${side}">${bg}<g transform="translate(${offset} ${offset}) scale(${scale})">${ball}</g></svg>`,
  );
};
const png = (buf, file) =>
  sharp(buf, { density: 300 }).png({ palette: true, compressionLevel: 9 }).toFile(file);

const out = resolve(import.meta.dirname, '../resources');
mkdirSync(out, { recursive: true });
// iOS / legacy Android: opaque square, the OS applies the mask. Ball at 80% of the side.
await png(svg(1024, 0.8, INK), resolve(out, 'icon-only.png'));
// Android adaptive icon: @capacitor/assets insets the layer by 16.7% (the 66dp safe zone of
// 108dp), so the ball fills 80% of this canvas: inside the visible mask with a thin ink margin.
await png(svg(1024, 0.8, null), resolve(out, 'icon-foreground.png'));
await png(svg(1024, 0, INK), resolve(out, 'icon-background.png'));
// Splash: ink canvas, small ball in the middle (both themes: the app opens on ink).
await png(svg(2732, 0.16, INK), resolve(out, 'splash.png'));
await png(svg(2732, 0.16, INK), resolve(out, 'splash-dark.png'));
writeFileSync(
  resolve(out, 'README.md'),
  'Sources for `@capacitor/assets` (icons and splash for Android and iOS). Generated by\n`node tools/make-assets.mjs` from the HoopTicker mark; do not edit by hand.\n',
);
console.log('resources written');
