#!/usr/bin/env node
// Writes src/environments/environment.generated.ts from apps/mobile/.env (or the process env).
// Runs before `ng serve` / `ng build`. The anon key is public by design (RLS protects data).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const envPath = resolve(root, '.env');
const values = {};
if (existsSync(envPath)) {
  for (const line of readFileSync(envPath, 'utf8').split('\n')) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    if (m) values[m[1]] = m[2].replace(/^"|"$/g, '');
  }
}
const get = (k, fallback = '') => process.env[k] ?? values[k] ?? fallback;

const out = `// Generated by tools/write-env.mjs from .env. Do not edit, do not commit.
export const generatedEnvironment = {
  supabaseUrl: ${JSON.stringify(get('SUPABASE_URL', 'http://127.0.0.1:54321'))},
  supabaseAnonKey: ${JSON.stringify(get('SUPABASE_ANON_KEY'))},
  revenueCatAppleKey: ${JSON.stringify(get('REVENUECAT_APPLE_KEY'))},
  revenueCatGoogleKey: ${JSON.stringify(get('REVENUECAT_GOOGLE_KEY'))},
  googleWebClientId: ${JSON.stringify(get('GOOGLE_WEB_CLIENT_ID'))},
  webUrl: ${JSON.stringify(get('WEB_URL', 'http://localhost:3000'))},
} as const;
`;
mkdirSync(resolve(root, 'src/environments'), { recursive: true });
writeFileSync(resolve(root, 'src/environments/environment.generated.ts'), out);
console.log('environment.generated.ts written');
