-- Sign-up consent and email digest preferences (plan of 2026-10-07, phase 2).
-- Users may update their own consent and digest frequency; the unsubscribe token is
-- generated by the database and only read by the service role (one-click unsubscribe links).

alter table public.profiles
  add column marketing_consent_at timestamptz,
  add column marketing_consent_source text check (marketing_consent_source in ('web', 'ios', 'android')),
  add column digest_frequency text not null default 'daily'
    check (digest_frequency in ('daily', 'weekly', 'off')),
  add column unsubscribe_token uuid not null default gen_random_uuid() unique;

comment on column public.profiles.marketing_consent_at is
  'When the user ticked the optional "product news and offers" box. Null = no consent: never send marketing email.';
comment on column public.profiles.digest_frequency is
  'Morning "Last night" email digest. Free users get weekly at most (job-morning enforces it); daily is Premium.';

grant update (marketing_consent_at, marketing_consent_source, digest_frequency) on public.profiles to authenticated;

-- One-click unsubscribe (RFC 8058): the link in every email carries the token; the edge
-- function calls this with the service role. Returns true when a profile matched.
create or replace function public.unsubscribe_by_token(p_token uuid, p_scope text default 'all')
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  matched integer;
begin
  if p_scope not in ('all', 'digest', 'marketing') then
    raise exception 'Unknown unsubscribe scope "%"', p_scope;
  end if;
  update public.profiles
  set
    digest_frequency = case when p_scope in ('all', 'digest') then 'off' else digest_frequency end,
    marketing_consent_at = case when p_scope in ('all', 'marketing') then null else marketing_consent_at end
  where unsubscribe_token = p_token;
  get diagnostics matched = row_count;
  return matched > 0;
end;
$$;
revoke execute on function public.unsubscribe_by_token from public, anon, authenticated;
