import 'server-only';
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@courtvault/shared';

/**
 * Server-side Supabase client with the anon key. The website only reads public data
 * (catalog, current prices, rankings) and inserts waitlist rows. Never used in the browser.
 */
export function supabase() {
  const url = process.env['NEXT_PUBLIC_SUPABASE_URL'];
  const key = process.env['NEXT_PUBLIC_SUPABASE_ANON_KEY'];
  if (!url || !key) throw new Error('NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY are required');
  return createClient<Database>(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
    global: {
      // Next.js extends fetch with caching: pages are regenerated by ISR, not on every request.
      fetch: (input, init) => fetch(input, { ...init, next: { revalidate: 3600, tags: ['catalog', 'prices'] } }),
    },
  });
}
